### PR TITLE
Added support for Safari

### PR DESCRIPTION
**Pull request by jumono**
Added support for safari, can't test it at the moment but it seems to work.

### CODE REVIEW

**Comment by pixeldesu** [comment]
I already implemented basic support for Safari (on the code-side), and wanted to implement the plist today, thanks you did this!

I will merge it, but most likely change a lot of stuff!

**Comment by jumono** [comment]
No problem, if you need any help on building it for Safari, I already have a developer certificate.
I'll try to work on a firefox port tonight too.

**Comment by pixeldesu** [comment]
I have an Apple Developer account myself, so I can get the certificate too, no problem!

And I'm going to make a seperate repository for the Firefox version, as I try to use in-browser APIs for that one might get quite handy for something like Rehatch!

**Comment by jumono** [comment]
Firefox seems to be way harder for injecting script and stuff. I'm actually trying at the moment to port it but I'll way for your repository to be ready. The main problem too is getting an equivalent of GetUrl() and stuff like that.

**Pull request merged**
